version: '3.4'
services:
  redis:
    image: "redis:alpine"
    deploy:
      replicas: 1
      update_config:
        failure_action: rollback
    networks:
      - kgs-network
  kgs-service:
    build: .
    ports:
      - "8081:8081"
    deploy:
      replicas: 3
      update_config:
        failure_action: rollback
        order: start-first
    links:
      - redis
    networks:
      - kgs-network

networks:
  kgs-network: