version: '3.4'
services:
  postgres:
    image: postgres:13
    deploy:
      replicas: 1
      update_config:
        failure_action: rollback
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=keys
    networks:
      - kgs-network
  kgs-service:
    build: .
    ports:
      - "8081:8081"
    deploy:
      replicas: 3
      update_config:
        failure_action: rollback
        order: start-first
    links:
      - postgres
    networks:
      - kgs-network

networks:
  kgs-network: